name: Deploy workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Install react-scripts
        working-directory: ./app
        run: npm install react-scripts
      
      - name: Build
        working-directory: ./app
        run: npm run build

      - name: Deploy
        run: npm run deploy