name: Deploy workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install

      - name: Configure Git User Identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Set Git user identity for deployment"
          git push origin main

      - name: Deploy
        run: npm run deploy
      